labels_dict = {'dad': 'dad',
               'mom': 'mom',
               'boy': 'boy',
               'girl': 'girl',
               'marriage': 'marriage',
               'baby': 'baby',
               'cold': 'cold',
               'food': 'food',
               'drink': 'drink',
               'cup': 'cup',
               'water': 'water',
               'cookie': 'cookie',
               'shirt': 'shirt',
               'mad': 'mad',
               'sorry': 'sorry',
               'love': 'love',
               'sad': 'sad'}
