name: pylint

on:
  pull_request:
  push:
    branches:
      - "master"

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Add Python to PATH
      run: |
        echo "::add-path::$(python -m site --user-base)/bin"

    - name: Run Pylint
      run: |
        pylint src/ tests/